#include <clibary.h>
#include <clibdscb.h>
#include <clibecb.h>
#include <clibenv.h>
#include <clibgrt.h>
#include <clibjes2.h>
#include <cliblist.h>
#include <clibmtt.h>
#include <clibppa.h>
#include <clibwto.h>
#include <racf.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "common.h"
#include "httpcgi.h"
#include "testapi.h"
#include "mvsmfmsg.h"
#include "zosmferr.h"          /* CATEGORY_SERVICE, REASON_SERVER_ERROR */
#include "buildid.h"           /* generated by the Makefile: #define BUILD_ID "<hash>" */

#ifndef BUILD_ID
#define BUILD_ID "unknown"     /* fallback if the generated header is absent */
#endif

/* fn=checkauth reply sentinels.  Kept out of the SAF rc range (0/4/8/12...) and
 * out of http_check_auth()'s -1 so a probe answer is never ambiguous. */
#define PROBE_NOT_RUN   (-901)  /* this call was not made for the given &via= */
#define PROBE_NO_ACEE   (-902)  /* unauthenticated: nothing to check against */
#define PROBE_BAD_ATTR  (-903)  /* unknown &attr=; nothing was called at all */

/* --- fn=syslog diagnostic ----------------------------------------------
 * Probe whether we can read the system log (SYSLOG) off the JES2 spool from
 * inside the httpd address space, reusing the same clibjes2 path jobsapi.c
 * uses for ordinary job spool.  Read-only.
 */
/* NOTE: MVSMF is link-edited RENT (loaded into read-only storage), so this
 * module must carry NO writable static/global data -- any write to one S0C4s
 * (protection).  The jesprint callback therefore keeps no counter; it just
 * streams each line, exactly like jobsapi.c's do_print_sysout_line().
 *
 * The Session arrives through jesprint()'s arg (libc370 #21/#22, issue #187);
 * before that signature existed the callback had to fish httpd/httpc out of
 * the per-task GRT anchors.                                                */
__asm__("\n&FUNC	SETC 'print_syslog_line'");
static int print_syslog_line(const char *line, unsigned linelen, void *arg) {
  Session *session = (Session *)arg; /* the httpx macro reads session->httpd */

  return http_printf(session->httpc, "%-*.*s\r\n", linelen, linelen, line);
}

/* JESPR_* as text, so the probe reports why a walk stopped rather than just
 * how much came out -- that distinction is the whole point of issue #186. */
__asm__("\n&FUNC	SETC 'jespr_reason_name'");
static const char *jespr_reason_name(int reason) {
  switch (reason) {
  case JESPR_END:     return "END";
  case JESPR_EMPTY:   return "EMPTY";
  case JESPR_IOERR:   return "IOERR";
  case JESPR_FOREIGN: return "FOREIGN";
  case JESPR_DSID:    return "DSID";
  case JESPR_LOOP:    return "LOOP";
  case JESPR_CAP:     return "CAP";
  case JESPR_STOPPED: return "STOPPED";
  case JESPR_NOBUF:   return "NOBUF";
  case JESPR_NOMEM:   return "NOMEM";
  case JESPR_OPENEND: return "OPENEND";
  }

  return "?";
}

/* --- fn=abend (ESTAE recovery test hook) --------------------------------
 * Deliberately faults INSIDE this CGI handler so the router's inner ESTAE
 * (libc370 @@try.c failed() -> tryrc()) catches it and emits MVSMF99E. This
 * exercises the CGI-level recovery path that a genuine handler abend takes
 * (e.g. the 2026-07-22 console crash) -- distinct from httpd's worker-level
 * recovery() path, which /abend in httpd already covers.
 *
 * HARD-GUARDED so it can never fire in a production deployment: it only
 * triggers when the server operator has explicitly set MVSMF_ABEND_TEST in
 * the server environment (a `//SYSENV DD` line `MVSMF_ABEND_TEST=1` in the
 * HTTPD started task; read here via getenv() from the CGI's runtime env,
 * which shares httpd's GRT). Unset -- the production default -- returns 400
 * and never faults. The value is server-side and operator-controlled; a
 * client cannot enable it by any request input.
 */
__asm__("\n&FUNC	SETC 'abend_test_enabled'");
static int abend_test_enabled(void) {
  const char *v = getenv("MVSMF_ABEND_TEST");
  return v && (v[0] == '1' || v[0] == 'Y' || v[0] == 'y');
}

/* --- fn=denyopen (issue #315) -------------------------------------------
 * Take a real S913 through the real ESTAE, to check that the router answers a
 * denial OPEN caught with the reference's authorization report rather than the
 * generic abend body.
 *
 * It exists because #228 made the natural way unreachable. That issue's own
 * live check was "MVSCE02 against SYS1.SECURE.CNTL(PROFILES)", which used to
 * abend -- the pre-checks now refuse it before the fopen(), which is the entire
 * point of them. So the only remaining way into this branch on a healthy system
 * is to open a data set without asking first, which is what this does.
 *
 * That is not a hole: the branch it verifies is a safety net for the cases the
 * pre-checks do not cover -- a pre-check and OPEN disagreeing, and the handlers
 * outside dsapi.c -- and a net nobody can reach is a net nobody can test.
 *
 * Gated exactly like fn=abend: an abend costs the CGI its storage subpool
 * (mvslovers/httpd#154), so this must never be reachable in production.
 * Handled before any response byte is written, so headers_sent is still 0 and
 * the router can send its recovery response.
 */
__asm__("\n&FUNC	SETC 'testDenyOpen'");
static int testDenyOpen(Session *session) {
  char *dsn = (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_DSN");
  FILE *fp;

  if (!abend_test_enabled()) {
    return sendErrorResponse(
        session, HTTP_STATUS_BAD_REQUEST, CATEGORY_SERVICE, RC_ERROR,
        REASON_SERVER_ERROR,
        "fn=denyopen is disabled. Set MVSMF_ABEND_TEST=1 in the server "
        "environment to enable the denial-recovery test hook.",
        NULL, 0);
  }

  if (!dsn)
    dsn = "SYS1.SECURE.CNTL(PROFILES)";

  /* No authorization check on purpose -- that is what is being bypassed. If
   * the caller may read this, nothing abends and the handle is closed again;
   * the probe is only meaningful with an id that may not. */
  fp = fopen(dsn, "r");
  if (fp) {
    fclose(fp);
    return sendErrorResponse(
        session, HTTP_STATUS_BAD_REQUEST, CATEGORY_SERVICE, RC_ERROR,
        REASON_SERVER_ERROR,
        "fn=denyopen: the data set opened, so nothing was denied. Use an id "
        "that may not read it.",
        NULL, 0);
  }

  /* fopen() returned NULL without abending: the open failed for some other
   * reason (not cataloged, wrong DSORG). Also not what this probe is for. */
  return sendErrorResponse(
      session, HTTP_STATUS_BAD_REQUEST, CATEGORY_SERVICE, RC_ERROR,
      REASON_SERVER_ERROR,
      "fn=denyopen: the open failed without abending, so it was not a denial.",
      NULL, 0);
}

__asm__("\n&FUNC	SETC 'testAbend'");
static int testAbend(Session *session) {
  if (!abend_test_enabled()) {
    return sendErrorResponse(
        session, HTTP_STATUS_BAD_REQUEST, CATEGORY_SERVICE, RC_ERROR,
        REASON_SERVER_ERROR,
        "fn=abend is disabled. Set MVSMF_ABEND_TEST=1 in the server "
        "environment to enable the ESTAE recovery test hook.",
        NULL, 0);
  }

  wtof(MSG_ABEND_TEST);

  /* Deliberate operation exception (S0C1): execute an invalid opcode
   * (a zero halfword, same idiom as httpd's /abend). This faults regardless
   * of PSW state and key and stores nothing -- unlike a wild store, which is
   * only harmless in problem state (testapi.c also runs MODESET SUP,KEY=ZERO
   * for fn=cmd). Caught by the router's try()/failed() ESTAE, which handles
   * any abend code identically. */
  __asm__ volatile("  DC	H'0'");

  return 0; /* not reached */
}

/* fn=jesabend -- abend with a JES handle open, the shape of issue #282.
 *
 * fn=abend proves the ESTAE catches; this proves the catch also releases the
 * JES2 spool data sets. Recovery must answer with MVSMF908I; without the
 * registration in session_register_jes() the handle is simply lost and the DCBs
 * stay open for the life of the address space (issue #286).
 */
__asm__("\n&FUNC	SETC 'testJesAbend'");
static int testJesAbend(Session *session) {
  JES *jes = NULL;

  if (!abend_test_enabled()) {
    return sendErrorResponse(
        session, HTTP_STATUS_BAD_REQUEST, CATEGORY_SERVICE, RC_ERROR,
        REASON_SERVER_ERROR,
        "fn=jesabend is disabled. Set MVSMF_ABEND_TEST=1 in the server "
        "environment to enable the ESTAE recovery test hook.",
        NULL, 0);
  }

  jes = jesopen();
  if (!jes) {
    return sendErrorResponse(session, HTTP_STATUS_INTERNAL_SERVER_ERROR,
                             CATEGORY_SERVICE, RC_SEVERE, REASON_SERVER_ERROR,
                             "jesopen() failed, nothing to leak", NULL, 0);
  }
  session_register_jes(session, jes);

  wtof(MSG_ABEND_TEST);

  __asm__ volatile("  DC	H'0'");

  return 0; /* not reached */
}

/* --- fn=storage (issue #287) --------------------------------------------
 * Sample the address space's free storage, so the degradation that ends in
 * S80A can be measured between load runs instead of reconstructed from a
 * console log that has already rolled out of the Master Trace Table.
 *
 * Two numbers, answering different questions:
 *
 *   largest  the biggest contiguous block GETMAIN would hand out right now.
 *            httpd LINKs MVSMF fresh per request and libc370's C startup
 *            takes a GETMAIN of the C stack (link_stack, from PPASTKLN) for
 *            the main stack, so once `largest` drops below that the next
 *            request cannot start -- S80A, before mvsMF's ESTAE exists.
 *   total    everything still free, counted in blocks of >= STG_GRAN
 *            (&total=1 only; see the warning on stg_comb()).
 *
 * `total` flat while `largest` shrinks is the fragmentation signature; both
 * falling together is an ordinary leak.  Either number alone cannot tell the
 * two apart, which is the whole reason the comb exists.
 *
 * Both are measured from *inside* a CGI request, so this task's own C stack
 * is already carved out of what is being reported, and each
 * sample is itself one more LINK.  Read the numbers accordingly.
 *
 * Probing uses the register form of GETMAIN/FREEMAIN, issued inline: MVSMF
 * is RENT, and the list forms (GETMAIN VC and friends) build their parameter
 * list in the code stream and store into it -- an S0C4 here.  The register
 * form is register setup plus SVC 10, which is also why the size has to be
 * bisected: VC would report the largest available block in one call, the R
 * form only ever answers yes or no.
 *
 * libc370's getmain() is deliberately not used: it WTOs on every failed
 * request, and a bisect fails by design on about half its probes -- that
 * would feed the instrument's own noise into the Master Trace Table that
 * consapi.c reads back out.
 */
#define STG_GRAN       4096u          /* probe resolution                   */
#define STG_MAX        0x00FFF000u    /* 16 MB - 4 K: the 24-bit ceiling    */
/* What one LINK actually asks for, per libc370 asm/@@crt0.asm: STACKLEN
 * (X'040088' = 262280, the whole STACK area, not just MAINSTK's 65536F) plus
 * L'CLIBPPA+7, then ANDed with X'00FFFFF8' -- rounded *down* to a doubleword,
 * which is why it lands on X'0400B8' and not one word higher.  262144 is the
 * round number this was first written against and it is too low: a largest
 * block between the two reads "fits" and does not. */
/* Measured, not recomputed: @@crt0/@@crt1 store the length they GETMAINed in
 * PPASTKLN (`ST R8,PPASTKLN`), so this reports what this very task's stack
 * actually cost and follows any `__stklen` change (mvsmf.c, #290) with no
 * second source of truth to drift.  0 when the PPA is unreachable. */
__asm__("\n&FUNC	SETC 'stg_link_stack'");
static unsigned stg_link_stack(void) {
  CLIBPPA *ppa = __ppaget();

  return ppa ? ppa->ppastkln : 0;
}
#define STG_COMB_MAX   256            /* blocks the &total=1 comb may hold  */
#define STG_SIZES_MAX  32             /* block sizes reported in the JSON   */

/* Conditional GETMAIN.  Returns NULL on any non-zero return code -- never
 * abends, never writes a message. */
__asm__("\n&FUNC	SETC 'stg_getmain'");
static void *stg_getmain(unsigned lv, unsigned sp) {
  int rc = 0;
  void *r1 = (void *)0;

  __asm__("GETMAIN RC,LV=(%2),SP=(%3)\n\t"
          "LR\t%0,15\n\t"
          "LR\t%1,1"
          : "=r"(rc), "=r"(r1)
          : "r"(lv), "r"(sp)
          : "0", "1", "14", "15");

  return rc ? (void *)0 : r1;
}

/* Conditional FREEMAIN.  Returns the return code: a non-zero one means this
 * probe just leaked what it took, which the caller reports rather than
 * swallows. */
__asm__("\n&FUNC	SETC 'stg_freemain'");
static int stg_freemain(void *addr, unsigned lv, unsigned sp) {
  int rc = 0;

  __asm__("FREEMAIN RC,A=(%1),LV=(%2),SP=(%3)\n\t"
          "LR\t%0,15"
          : "=r"(rc)
          : "r"(addr), "r"(lv), "r"(sp)
          : "0", "1", "14", "15");

  return rc;
}

/* Largest obtainable block, bisected to STG_GRAN.  `hi` is a size known (or
 * assumed) to fail; the return value is the largest multiple of STG_GRAN
 * that succeeded, 0 if not even one page is left.  Every probe gives its
 * block straight back, so the subpool is left exactly as it was found. */
__asm__("\n&FUNC	SETC 'stg_largest'");
static unsigned stg_largest(unsigned sp, unsigned hi, int *probes,
                            int *free_errors) {
  unsigned lo = 0; /* largest size known to succeed */

  while (hi - lo > STG_GRAN) {
    unsigned mid = (lo + (hi - lo) / 2) & ~(STG_GRAN - 1);
    void *p;

    if (mid <= lo)
      break;

    (*probes)++;
    p = stg_getmain(mid, sp);
    if (p) {
      if (stg_freemain(p, mid, sp) != 0)
        (*free_errors)++;
      lo = mid;
    } else {
      hi = mid;
    }
  }

  return lo;
}

/* Total free storage, by taking the largest block over and over until
 * nothing of STG_GRAN is left, then giving all of it back.
 *
 * WARNING: for the length of the loop this task holds every free byte in the
 * subpool.  A request arriving in that window fails its startup GETMAIN --
 * S80A, and per mvslovers/httpd#154 that abend leaks storage permanently,
 * i.e. the instrument would corrupt the very quantity it measures.  Sample
 * with &total=1 only between load runs, never during one.
 *
 * Nothing here may allocate between the take loop and the give-back loop.
 * The block table is on the stack for that reason (and because MVSMF is
 * RENT), which is what bounds it at STG_COMB_MAX. */
__asm__("\n&FUNC	SETC 'stg_comb'");
static void stg_comb(unsigned sp, unsigned *sizes, int max_sizes, int *nsizes,
                     unsigned *total, int *nblocks, int *truncated,
                     int *probes, int *free_errors) {
  void *addr[STG_COMB_MAX];
  unsigned len[STG_COMB_MAX];
  unsigned hi = STG_MAX + STG_GRAN;
  unsigned sum = 0;
  int n = 0;
  int i;

  while (n < STG_COMB_MAX) {
    unsigned sz = stg_largest(sp, hi, probes, free_errors);
    void *p;

    if (sz < STG_GRAN)
      break;

    p = stg_getmain(sz, sp);
    if (!p)
      break; /* lost the race against another task; stop with what we hold */

    addr[n] = p;
    len[n] = sz;
    sum += sz;
    hi = sz + STG_GRAN; /* nothing left can be larger than this block */
    n++;
  }

  *truncated = (n == STG_COMB_MAX);
  *nblocks = n;
  *total = sum;

  *nsizes = (n < max_sizes) ? n : max_sizes;
  for (i = 0; i < *nsizes; i++)
    sizes[i] = len[i];

  while (n-- > 0) {
    if (stg_freemain(addr[n], len[n], sp) != 0)
      (*free_errors)++;
  }
}

int testHandler(Session *session) {
  int rc = 0;
  char *fn = NULL;

  fn = (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_FN");
  if (!fn)
    fn = "help";

  /* fn=abend must be handled before any response bytes are written: on the
   * enabled path it faults with headers_sent still 0, so the router can send
   * its 500 recovery response after failed() retries. */
  if (strcmp(fn, "abend") == 0)
    return testAbend(session);

  if (strcmp(fn, "jesabend") == 0)
    return testJesAbend(session);

  if (strcmp(fn, "denyopen") == 0)
    return testDenyOpen(session);

  session->headers_sent = 1;
  if ((rc = http_resp(session->httpc, 200)) < 0)
    goto quit;
  if ((rc = http_printf(session->httpc,
                        "Content-Type: application/json\r\n\r\n")) < 0)
    goto quit;

  /* --- fn=listds ------------------------------------------------ */
  if (strcmp(fn, "listds") == 0) {
    char *level =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_LEVEL");
    char *filter =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_FILTER");
    DSLIST **dslist = NULL;
    unsigned i, count;

    if (!level)
      level = "SYS1";

    dslist = __listds(level, "NONVSAM VOLUME", filter);

    rc = http_printf(
        session->httpc,
        "{ \"fn\": \"listds\", \"level\": \"%s\", \"filter\": \"%s\",\n", level,
        filter ? filter : "(null)");
    if (rc < 0)
      goto quit;

    rc = http_printf(session->httpc, "  \"items\": [\n");
    if (rc < 0)
      goto quit;

    count = dslist ? array_count(&dslist) : 0;
    for (i = 0; i < count; i++) {
      DSLIST *ds = dslist[i];
      if (!ds)
        continue;
      rc = http_printf(session->httpc,
                       "    %s{ \"dsn\": \"%s\", \"vol\": \"%.6s\","
                       " \"dsorg\": \"%.4s\", \"recfm\": \"%.4s\","
                       " \"lrecl\": %d, \"blksize\": %d }\n",
                       i > 0 ? "," : " ", ds->dsn, ds->volser, ds->dsorg,
                       ds->recfm, ds->lrecl, ds->blksize);
      if (rc < 0)
        goto quit;
    }

    rc = http_printf(session->httpc, "  ], \"count\": %u }\n", count);

    if (dslist)
      __freeds(&dslist);

    /* --- fn=locate ------------------------------------------------ */
  } else if (strcmp(fn, "locate") == 0) {
    char *dsn =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_DSN");
    LOCWORK locwork = {0};
    int loc_rc;

    if (!dsn)
      dsn = "SYS1.MACLIB";

    loc_rc = __locate(dsn, &locwork);

    rc = http_printf(session->httpc,
                     "{ \"fn\": \"locate\", \"dsn\": \"%s\","
                     " \"rc\": %d, \"volser\": \"%.6s\" }\n",
                     dsn, loc_rc, locwork.volser);

    /* --- fn=syslog (stepped probe) -------------------------------- */
    /* Bisect via &step=N.  Each step that returns normally flushes its
     * output; the highest step still producing output is the last that
     * worked, the next (empty body) is the call that abends.            */
  } else if (strcmp(fn, "syslog") == 0) {
    char *stepv =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_STEP");
    int step = stepv ? atoi(stepv) : 0;
    JES *jes = NULL;
    JESJOB **jobs = NULL;
    unsigned jc = 0;

    http_printf(session->httpc, "syslog probe step=%d: START\r\n", step);

    if (step >= 1) {
      jes = jesopen();
      session_register_jes(session, jes);
      http_printf(session->httpc, "step1 jesopen -> %s\r\n",
                  jes ? "OK" : "NULL");
    }

    if (step >= 2 && jes) {
      jobs = jesjob(jes, "SYSLOG", FILTER_JOBNAME, 1);
      jc = jobs ? array_count(&jobs) : 0;
      http_printf(session->httpc, "step2 jesjob -> %s count=%u\r\n",
                  jobs ? "OK" : "NULL", jc);
    }

    if (step >= 3 && jobs) {
      unsigned ji;
      for (ji = 0; ji < jc; ji++) {
        JESJOB *job = jobs[ji];
        http_printf(session->httpc, "step3 entry %u jobid=%-8.8s jesdd=%s\r\n",
                    ji, job ? (char *)job->jobid : "(null)",
                    (job && job->jesdd) ? "set" : "NULL");
      }
    }

    if (step >= 4 && jobs) {
      unsigned ji, di;
      for (ji = 0; ji < jc; ji++) {
        JESJOB *job = jobs[ji];
        unsigned dc;
        if (!job || !job->jesdd)
          continue;
        dc = array_count(&job->jesdd);
        for (di = 0; di < dc; di++) {
          JESDD *dd = job->jesdd[di];
          if (!dd)
            continue;
          http_printf(session->httpc,
                      "step4 entry %u dd %u dsid=%u mttr=%u records=%u\r\n", ji,
                      di, dd->dsid, dd->mttr, dd->records);
        }
      }
    }

    if (step >= 5 && jobs) {
      unsigned ji, di;
      for (ji = 0; ji < jc; ji++) {
        JESJOB *job = jobs[ji];
        unsigned dc;
        if (!job || !job->jesdd)
          continue;
        dc = array_count(&job->jesdd);
        for (di = 0; di < dc; di++) {
          JESDD *dd = job->jesdd[di];
          JESPRST st;
          int prc;
          if (!dd || !dd->mttr)
            continue;
          http_printf(session->httpc,
                      "----- jobid=%-8.8s dd=%-8.8s dsid=%u -----\r\n",
                      (char *)job->jobid, (char *)dd->ddname, dd->dsid);
          prc = jesprint(jes, job, dd->dsid, print_syslog_line, session, &st);
          http_printf(session->httpc,
                      "----- rc=%d reason=%s blocks=%u lines=%u mttr=%08X "
                      "records=%u -----\r\n",
                      prc, jespr_reason_name(st.reason), st.blocks, st.lines,
                      st.mttr, dd->records);
        }
      }
    }

    if (jobs)
      jesjobfr(&jobs);
    session_jesclose(session, &jes);

    rc = http_printf(session->httpc, "DONE step=%d\r\n", step);

    /* --- fn=mtt (master trace table = LIVE console data) ---------- */
    /* The real source for the console feature: clibmtt snapshots the
     * Master Trace Table (live WTOs + commands) -- no spin needed.     */
  } else if (strcmp(fn, "mtt") == 0) {
    char *stepv =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_STEP");
    int step = stepv ? atoi(stepv) : 3;
    CMTT *cmtt = NULL;
    MTENTRY **arr = NULL;
    unsigned n = 0, i;

    http_printf(session->httpc, "mtt probe step=%d START\r\n", step);

    if (step >= 1) {
      cmtt = cmtt_new();
      http_printf(session->httpc, "step1 cmtt_new -> %s\r\n",
                  cmtt ? "OK" : "NULL");
    }

    if (step >= 2 && cmtt) {
      arr = cmtt_get_array(cmtt);
      n = arr ? array_count(&arr) : 0;
      http_printf(session->httpc, "step2 get_array -> %s count=%u\r\n",
                  arr ? "OK" : "NULL", n);
    }

    if (step >= 3 && arr) {
      for (i = 0; i < n; i++) {
        MTENTRY *e = arr[i];
        if (!e)
          continue;
        http_printf(session->httpc, "%-*.*s\r\n", (int)e->mtentlen,
                    (int)e->mtentlen, e->mtentdat);
      }
    }

    if (cmtt)
      cmtt_free(&cmtt);

    rc = http_printf(session->httpc, "DONE step=%d\r\n", step);

    /* --- fn=cmd (round-trip: issue MVS command + find it in MTT) -- */
    /* Issues an operator command via SVC 34 (MGCR, like brexx R_console),
     * then polls the MTT until the echo shows up, and dumps the tail so
     * we can see the command + its responses.  Default 'D T' (harmless). */
  } else if (strcmp(fn, "cmd") == 0) {
    char *cmdtext =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_CMD");
    unsigned char cmdbuf[128];
    unsigned char *cmdp = cmdbuf;
    unsigned cmdlen, i, n = 0, from;
    int tries;
    CMTT *cmtt = NULL;
    MTENTRY **arr = NULL;

    if (!cmdtext)
      cmdtext = "D T";
    cmdlen = strlen(cmdtext);
    if (cmdlen > 100)
      cmdlen = 100;

    http_printf(session->httpc, "cmd probe: issuing '%s' via SVC 34 (MGCR)\r\n",
                cmdtext);

    /* build SVC 34 command buffer (IEECDCM dcminlgn/mcsfl/dcminput) */
    memset(cmdbuf, 0, sizeof(cmdbuf));
    cmdbuf[1] = 104;
    memset(&cmdbuf[4], ' ', 124);
    memcpy(&cmdbuf[4], cmdtext, cmdlen);

    /* issue: supervisor/key0 -> SVC 34 -> back to problem/key8 */
    __asm__("MODESET MODE=SUP,KEY=ZERO");
    __asm__ volatile("  L   1,%0\n"
                     "  SLR 0,0\n"
                     "  SVC 34"
                     :
                     : "m"(cmdp)
                     : "0", "1", "14", "15");
    __asm__("MODESET MODE=PROB,KEY=NZERO");

    /* poll the MTT until our command echo appears (each cmtt_new()
     * re-snapshots and gives the responses time to land) */
    for (tries = 0; tries < 15; tries++) {
      int hit = 0;
      if (cmtt)
        cmtt_free(&cmtt);
      cmtt = cmtt_new();
      arr = cmtt ? cmtt_get_array(cmtt) : NULL;
      n = arr ? array_count(&arr) : 0;
      for (i = (n > 40 ? n - 40 : 0); i < n; i++) {
        MTENTRY *e = arr[i];
        char tmp[128];
        int len = e ? (int)e->mtentlen : 0;
        if (!e)
          continue;
        if (len > 127)
          len = 127;
        memcpy(tmp, e->mtentdat, len);
        tmp[len] = '\0';
        if (strstr(tmp, cmdtext)) {
          hit = 1;
          break;
        }
      }
      if (hit)
        break;
    }

    http_printf(session->httpc, "MTT count=%u after %d poll(s), tail:\r\n", n,
                tries + 1);
    from = (n > 50) ? n - 50 : 0;
    for (i = from; i < n; i++) {
      MTENTRY *e = arr[i];
      if (!e)
        continue;
      http_printf(session->httpc, "%-*.*s\r\n", (int)e->mtentlen,
                  (int)e->mtentlen, e->mtentdat);
    }

    if (cmtt)
      cmtt_free(&cmtt);

    rc = http_printf(session->httpc, "DONE\r\n");

    /* --- fn=version (deployed build marker) ----------------------- */
  } else if (strcmp(fn, "version") == 0) {
    rc = http_printf(
        session->httpc,
        "{ \"fn\": \"version\", \"version\": \"%s\", \"build\": \"%s\" }\n",
        VERSION, BUILD_ID);

    /* --- fn=userid (diagnose http_get_userid() vs. direct ACEE decode) */
    /* Cross-checks httpd's HTTPX http_get_userid() export against a manual
     * ACEE decode -- the same length-prefixed aceeuser field ussapi.c
     * already reads successfully for UFS ownership -- to isolate the
     * garbage-userid behavior seen from http_get_userid() during #164
     * job-submission testing. No secrets here: just a userid either way. */
  } else if (strcmp(fn, "userid") == 0) {
    ACEE *acee = http_get_acee(session->httpc);
    UCHAR buf[64] = {0};
    UCHAR *ret;
    char direct[9] = {0};
    char hex[64 * 2 + 1] = {0};
    unsigned i;

    ret = http_get_userid(session->httpc, buf, sizeof(buf));

    if (acee) {
      unsigned char ulen = (unsigned char)acee->aceeuser[0];
      if (ulen > 8)
        ulen = 8;
      memcpy(direct, acee->aceeuser + 1, ulen);
    }

    for (i = 0; i < sizeof(buf); i++) {
      sprintf(&hex[i * 2], "%02X", buf[i]);
    }

    rc = http_printf(
        session->httpc,
        "{ \"fn\": \"userid\", \"acee\": \"%s\","
        " \"direct_from_acee\": \"%s\","
        " \"http_get_userid_ret\": \"%s\", \"strlen\": %d,"
        " \"hex\": \"%s\" }\n",
        acee ? "non-null" : "NULL", direct, ret ? "non-null" : "NULL",
        (int)strlen((char *)buf), hex);

    /* --- fn=password (exercise http_get_password()) ---------------- */
    /* Verifies httpd's HTTPX http_get_password() export (mvslovers/httpd#111),
     * which decrypts the caller's password from the session credential -- the
     * value job submission puts on the JOB card. The plaintext is a secret, so
     * it is shown only with &reveal=1; otherwise it is masked. Auth-gated: a
     * caller only ever sees their own password (which they already know). */
  } else if (strcmp(fn, "password") == 0) {
    UCHAR buf[64] = {0};
    UCHAR *ret;
    char *reveal =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_REVEAL");
    int len;
    char masked[64] = {0};
    int i;

    ret = http_get_password(session->httpc, buf, sizeof(buf));
    len = (int)strlen((char *)buf);

    for (i = 0; i < len && i < (int)sizeof(masked) - 1; i++) {
      masked[i] = '*';
    }

    rc = http_printf(
        session->httpc,
        "{ \"fn\": \"password\","
        " \"http_get_password_ret\": \"%s\", \"strlen\": %d,"
        " \"value\": \"%s\" }\n",
        ret ? "non-null" : "NULL", len,
        (reveal && strcmp(reveal, "1") == 0) ? (char *)buf : masked);

    /* --- fn=env (does the CGI see httpd's //SYSENV?) --------------- */
    /* The abend test hook is gated on getenv("MVSMF_ABEND_TEST"), which only
     * works because httpd and the CGI share one CLIBGRT -- the CGI reads the
     * environment httpd's @@START loaded from //SYSENV. When that gate does
     * not open there are two indistinguishable causes: the DD/member was not
     * in place at server start, or the CGI is not seeing httpd's environment
     * at all. Listing what this CGI actually has separates them: names but no
     * MVSMF_* means the member was empty at start; an empty list means the
     * environment is not shared.
     *
     * Names are always safe to show; values are not (httpd's environment is
     * the server operator's, not the caller's), so only MVSMF_* values are
     * printed -- those are our own test flags and carry no secrets.
     *
     * Read grt->grtenv, which is where the environment actually lives. The
     * __envvar/__envsiz pair exported by clibenv.h is a legacy symbol that
     * stays 0 (libc370 @@envvar.c), so reading it reports an empty
     * environment no matter what is loaded -- a false negative that reads
     * exactly like "the CGI does not see httpd's environment". getenv()
     * resolves through __findenv() -> __grtget()->grtenv (@@finden.c:18), so
     * walking that array answers the same question getenv() does. */
  } else if (strcmp(fn, "env") == 0) {
    CLIBGRT *grt = __grtget();
    unsigned count = (grt && grt->grtenv) ? arraycount(&grt->grtenv) : 0;
    unsigned i;
    int shown = 0;

    rc = http_printf(session->httpc,
                     "{ \"fn\": \"env\", \"grt\": \"%s\","
                     " \"grtenv\": \"%s\", \"count\": %u, \"items\": [",
                     grt ? "non-null" : "NULL",
                     (grt && grt->grtenv) ? "non-null" : "NULL", count);
    if (rc < 0)
      goto quit;

    for (i = 0; i < count; i++) {
      __ENVVAR *ev = (__ENVVAR *)grt->grtenv[i];
      const char *name;

      if (!ev || !ev->name)
        continue;
      name = ev->name;

      if (strncmp(name, "MVSMF_", 6) == 0) {
        rc = http_printf(session->httpc,
                         "%s{ \"name\": \"%s\", \"value\": \"%s\" }",
                         shown ? ", " : " ", name, ev->value ? ev->value : "");
      } else {
        rc = http_printf(session->httpc, "%s{ \"name\": \"%s\" }",
                         shown ? ", " : " ", name);
      }
      if (rc < 0)
        goto quit;
      shown++;
    }

    rc = http_printf(session->httpc, " ] }\n");

    /* --- fn=storage (free storage sample, issue #287) -------------- */
  } else if (strcmp(fn, "storage") == 0) {
    char *spv = (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_SP");
    char *totalv =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_TOTAL");
    char *holdv =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_HOLD");
    int spn = spv ? atoi(spv) : 0;
    unsigned sp = (unsigned)spn;
    int want_total = totalv && (totalv[0] == '1' || totalv[0] == 'y' ||
                                totalv[0] == 'Y');
    /* &hold=<seconds> (cap 10): after measuring, KEEP the largest block
     * allocated for that long before freeing it.  Concurrent requests must
     * then start their 262328-byte C stack in what remains -- which is how
     * both halves of the #287 fragmentation claim get proven live: a request
     * that fails U0801 while the holes are the only space left proves the
     * failure signature AND that a fenced-off hole cannot hold a stack.
     *
     * This is deliberate fault injection against a live server, so it is
     * gated exactly like fn=abend: without MVSMF_ABEND_TEST in the server
     * environment the parameter is ignored and reported as such. */
    int hold = holdv ? atoi(holdv) : 0;
    int hold_denied = 0;

    if (hold < 0)
      hold = 0;
    if (hold > 10)
      hold = 10;
    if (hold && !abend_test_enabled()) {
      hold = 0;
      hold_denied = 1;
    }

    if (spn < 0 || spn > 127) {
      rc = http_printf(session->httpc,
                       "{ \"fn\": \"storage\", \"error\": \"sp must be 0..127;"
                       " subpools above 127 need supervisor state\" }\n");
    } else {
      unsigned largest;
      unsigned sizes[STG_SIZES_MAX];
      unsigned total = 0;
      int probes = 0, free_errors = 0;
      int nblocks = 0, nsizes = 0, truncated = 0;
      char largest_at[16] = "";
      char stack_at[16] = "";
      void *p;
      int i;

      /* This request's own stack: where in the region the current LINK
       * landed, and hence which end of it the 262 K came out of. */
      sprintf(stack_at, "0x%06X", (unsigned)(unsigned long)&probes);

      largest = stg_largest(sp, STG_MAX + STG_GRAN, &probes, &free_errors);
      if (largest) {
        p = stg_getmain(largest, sp);
        if (p) {
          sprintf(largest_at, "0x%06X", (unsigned)(unsigned long)p);
          if (hold) {
            ECB ecb = 0;
            /* BINTVL is in hundredths of a second.  A failed timer (negative
             * rc) means no wait happened -- fine here, the block is simply
             * given back at once and `held` reports what really occurred. */
            if (ecb_timed_wait(&ecb, (unsigned)hold * 100u, 1) < 0)
              hold = 0;
          }
          if (stg_freemain(p, largest, sp) != 0)
            free_errors++;
        }
      }

      if (want_total)
        stg_comb(sp, sizes, STG_SIZES_MAX, &nsizes, &total, &nblocks,
                 &truncated, &probes, &free_errors);

      rc = http_printf(session->httpc,
                       "{ \"fn\": \"storage\", \"sp\": %u, \"largest\": %u,"
                       " \"largest_at\": \"%s\", \"link_stack\": %u,"
                       " \"granularity\": %u, \"stack_at\": \"%s\"",
                       sp, largest, largest_at, stg_link_stack(), STG_GRAN,
                       stack_at);
      if (rc < 0)
        goto quit;

      if (want_total) {
        rc = http_printf(session->httpc,
                         ", \"total\": %u, \"blocks\": %d,"
                         " \"truncated\": %s, \"sizes\": [",
                         total, nblocks, truncated ? "true" : "false");
        if (rc < 0)
          goto quit;

        for (i = 0; i < nsizes; i++) {
          rc = http_printf(session->httpc, "%s%u", i > 0 ? ", " : "",
                           sizes[i]);
          if (rc < 0)
            goto quit;
        }

        rc = http_printf(session->httpc, "]");
        if (rc < 0)
          goto quit;
      }

      if (hold || hold_denied) {
        rc = http_printf(session->httpc, ", \"held\": %d, \"hold_denied\": %s",
                         hold, hold_denied ? "true" : "false");
        if (rc < 0)
          goto quit;
      }

      rc = http_printf(session->httpc, ", \"probes\": %d, \"free_errors\": %d"
                                       " }\n",
                       probes, free_errors);
    }

    /* --- fn=job (raw JCT termination bits, issue #305) -------------- */
    /* A job that fails allocation is reported "CC 0000": the step never ran,
     * so no condition code was ever set, and the converter RC is 0 because
     * the JCL passed conversion.  What MVS reports as IEF453I JOB FAILED
     * lives in JCTJTFLG, which process_job() reads only for JESJOB_ABD.
     * This dumps the raw bytes so the discriminator can be chosen from a
     * measurement instead of from the header comment.  Read-only. */
  } else if (strcmp(fn, "job") == 0) {
    char *jn = (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_JOBNAME");
    JES *jes = NULL;
    JESJOB **jobs = NULL;
    unsigned jc = 0;
    unsigned ji;
    int first = 1;

    if (!jn || !*jn) {
      rc = http_printf(session->httpc,
                       "{ \"fn\": \"job\", \"error\": \"jobname= required\" }\n");
      goto quit;
    }

    jes = jesopen();
    if (!jes) {
      rc = http_printf(session->httpc,
                       "{ \"fn\": \"job\", \"error\": \"jesopen failed\" }\n");
      goto quit;
    }
    session_register_jes(session, jes);

    jobs = jesjob(jes, jn, FILTER_JOBNAME, 0);
    jc = jobs ? array_count(&jobs) : 0;

    if ((rc = http_printf(session->httpc,
                          "{ \"fn\": \"job\", \"jobname\": \"%s\","
                          " \"count\": %u, \"items\": [\n", jn, jc)) < 0)
      goto quit_job;

    for (ji = 0; ji < jc; ji++) {
      JESJOB *job = jobs[ji];
      unsigned comp;
      unsigned hi, abend, maxcc;
      unsigned char jtflg;
      char retcode[16];

      if (!job)
        continue;

      comp  = job->completion;
      hi    = (comp >> 24) & 0xFF;
      abend = (comp >> 12) & 0xFFF;
      maxcc =  comp        & 0xFFF;
      jtflg = job->jtflg;

      /* mirrors process_job() in jobsapi.c -- keep the two in step */
      if (!(job->q_type & (_OUTPUT | _HARDCPY))) {
        snprintf(retcode, sizeof(retcode), "%s", "(null)");
      } else if (hi == 0x77) {
        if (abend)
          snprintf(retcode, sizeof(retcode), "ABEND S%03X", abend);
        else if ((jtflg & JESJOB_ABD) && maxcc)
          snprintf(retcode, sizeof(retcode), "ABEND U%04d", maxcc);
        else if (jtflg == JESJOB_JF)
          snprintf(retcode, sizeof(retcode), "%s", "JCL ERROR");
        else
          snprintf(retcode, sizeof(retcode), "CC %04d", maxcc);
      } else if (comp == 4 || comp == 8 || comp == 36) {
        snprintf(retcode, sizeof(retcode), "%s", "JCL ERROR");
      } else {
        snprintf(retcode, sizeof(retcode), "%s", "(null)");
      }

      if ((rc = http_printf(session->httpc,
              "%s  { \"jobid\": \"%-8.8s\", \"q_type\": \"%02X\","
              " \"q_flag1\": \"%02X\", \"q_flag2\": \"%02X\","
              " \"completion\": \"%08X\", \"comp_hi\": \"%02X\","
              " \"abend\": %u, \"maxcc\": %u,"
              " \"jtflg\": \"%02X\", \"JF\": %s, \"CF\": %s, \"ABD\": %s,"
              " \"retcode\": \"%s\" }\n",
              first ? " " : " ,",
              (char *)job->jobid,
              (unsigned)job->q_type, (unsigned)job->q_flag1,
              (unsigned)job->q_flag2, comp, hi, abend, maxcc,
              (unsigned)jtflg,
              (jtflg & JESJOB_JF)  ? "true" : "false",
              (jtflg & JESJOB_CF)  ? "true" : "false",
              (jtflg & JESJOB_ABD) ? "true" : "false",
              retcode)) < 0)
        goto quit_job;

      first = 0;
    }

    rc = http_printf(session->httpc, " ] }\n");

  quit_job:
    if (jobs)
      jesjobfr(&jobs);
    session_jesclose(session, &jes);
    if (rc < 0)
      goto quit;

    /* --- fn=intrdr (internal-reader open/close cycles, issue #294) -- */
  } else if (strcmp(fn, "intrdr") == 0) {
    /* Bisect for mvslovers/libc370#115: a job submit permanently costs the
     * address space one 4 K page (mvslovers/httpd#195).  This runs only the
     * open/close half -- jesiropn() dynallocs a fresh INTRDR SYSOUT DD and
     * opens the JES2 ACB, jesircls() ENDREQs and closes it -- and never
     * writes a record, so JES2 discards the input and no job is created.
     *
     * Deliberately NO storage measurement in here: sample from outside with
     * fn=storage&total=1 around this call, so the request-subpool reclaim
     * (#175) runs between the cycles and the measurement -- the same
     * conditions under which the submit page was shown to survive.
     *
     * An open failure stops the loop: every further cycle would fail the
     * same way, and each attempt costs a dynalloc.  A close rc is counted
     * but stops nothing -- jesircls() releases the handle regardless. */
    char *nv = (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_N");
    int want = nv ? atoi(nv) : 1;
    int ok = 0;
    int open_rc = 0;
    int close_errors = 0;
    int first_close_rc = 0;
    int i;

    if (want < 1)
      want = 1;
    if (want > 25)
      want = 25;

    for (i = 0; i < want; i++) {
      VSFILE *ir = NULL;
      int crc;

      open_rc = jesiropn(&ir);
      if (open_rc || !ir) {
        if (!open_rc)
          open_rc = -1; /* NULL handle with rc 0: report it as a failure */
        break;
      }

      crc = jesircls(ir);
      if (crc) {
        close_errors++;
        if (!first_close_rc)
          first_close_rc = crc;
      }
      ok++;
    }

    rc = http_printf(session->httpc,
                     "{ \"fn\": \"intrdr\", \"cycles\": %d, \"ok\": %d,"
                     " \"open_rc\": %d, \"close_errors\": %d,"
                     " \"first_close_rc\": %d }\n",
                     want, ok, open_rc, close_errors, first_close_rc);

    /* --- fn=checkauth (issue #228) --------------------------------- */
    /* First CGI consumer of httpd's http_check_auth() vector entry, and the
     * measurement tool for #228's attribute column. It exists before any
     * handler is gated, for two reasons that both fail late otherwise.
     *
     * The vector resolves into the RUNNING httpd (httpx is
     * http_get_httpx(session->httpd)), so a live build older than the entry
     * makes the macro dereference past what the server actually filled. That
     * is an abend, not a link error, and `make deps` cannot see it -- the same
     * shape as the httpstat() lesson.
     *
     * And the attribute a given operation needs is a claim about what RAKF
     * enforces, not about what this code intends. RAKF is not RACF and is not
     * in the mvslovers org; measuring what it answers beats proposing a table.
     *
     * &via=raw (the default) calls libc370's racf_auth() directly -- no vector,
     * so it cannot be taken down by the half being verified -- and shows the
     * UNNORMALIZED SAF rc, the only way to see rc 4 ("no profile covers this")
     * as distinct from rc 0. &via=vector adds the httpd call; &via=both runs
     * raw first so its answer is already on the wire if the vector call dies.
     *
     * Read-only: RACHECK answers a question, it changes nothing. A denial does
     * write the security log entry RAKF writes for any refusal.
     */
  } else if (strcmp(fn, "checkauth") == 0) {
    char *dsn =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_DSN");
    char *cls =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_CLASS");
    char *attrname =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_ATTR");
    char *via =
        (char *)http_get_env(session->httpc, (const UCHAR *)"QUERY_VIA");
    ACEE *acee = http_get_acee(session->httpc);
    int attr = RACF_ATTR_READ;
    int raw_rc = PROBE_NOT_RUN;
    int vec_rc = PROBE_NOT_RUN;

    if (!dsn)
      dsn = "SYS1.PARMLIB";
    if (!cls)
      cls = "DATASET";
    if (!via)
      via = "raw";
    if (!attrname)
      attrname = "read";

    /* An unknown &attr= must not silently mean READ: racf_auth() maps an
     * invalid value to ALTER, so a typo would measure the strictest attribute
     * while the reply claimed the one that was asked for. */
    if (strcmp(attrname, "read") == 0) {
      attr = RACF_ATTR_READ;
    } else if (strcmp(attrname, "update") == 0) {
      attr = RACF_ATTR_UPDATE;
    } else if (strcmp(attrname, "control") == 0) {
      attr = RACF_ATTR_CONTROL;
    } else if (strcmp(attrname, "alter") == 0) {
      attr = RACF_ATTR_ALTER;
    } else {
      attr = PROBE_BAD_ATTR;
    }

    if (attr != PROBE_BAD_ATTR) {
      if (strcmp(via, "raw") == 0 || strcmp(via, "both") == 0) {
        raw_rc = acee ? racf_auth(acee, cls, dsn, attr) : PROBE_NO_ACEE;
      }
      if (strcmp(via, "vector") == 0 || strcmp(via, "both") == 0) {
        vec_rc = http_check_auth(session->httpc, cls, dsn, attr);
      }
    }

    rc = http_printf(session->httpc,
                     "{ \"fn\": \"checkauth\", \"class\": \"%s\","
                     " \"resource\": \"%s\", \"attr\": \"%s\","
                     " \"attr_value\": %d, \"via\": \"%s\","
                     " \"acee\": \"%s\","
                     " \"racf_auth_rc\": %d, \"http_check_auth_rc\": %d }\n",
                     cls, dsn, attrname, attr, via,
                     acee ? "non-null" : "NULL", raw_rc, vec_rc);

    /* --- fn=help (default) ---------------------------------------- */
  } else {
    rc = http_printf(
        session->httpc,
        "{ \"fn\": \"help\", \"usage\": ["
        " \"?fn=version             (deployed version + git build id)\","
        " \"?fn=listds&level=HLQ&filter=HLQ.X*\","
        " \"?fn=locate&dsn=SYS1.MACLIB\","
        " \"?fn=syslog&step=0..5  (JES2 spool SYSLOG probe)\","
        " \"?fn=mtt&step=1..3     (Master Trace Table dump)\","
        " \"?fn=cmd&cmd=D+T       (issue MVS command via SVC34, find in MTT)\","
        " \"?fn=storage&sp=0&total=0|1&hold=N (free storage sample; total=1 briefly holds all"
        " of it; hold=N keeps the largest block N seconds -- needs MVSMF_ABEND_TEST=1)\","
        " \"?fn=intrdr&n=1..25      (internal-reader open/close cycles, no records; libc370#115 bisect)\","
        " \"?fn=job&jobname=NAME    (raw JCT completion + JCTJTFLG bits per job; mvsmf#305)\","
        " \"?fn=userid              (http_get_userid() vs. direct ACEE decode)\","
        " \"?fn=checkauth&dsn=DS&attr=read|update|control|alter&via=raw|vector|both  (RACHECK probe; mvsmf#228)\","
        " \"?fn=password&reveal=0|1 (http_get_password() export; reveal=1 = plaintext)\","
        " \"?fn=abend               (force S0C1 -> ESTAE recovery test; needs MVSMF_ABEND_TEST=1)\","
        " \"?fn=denyopen&dsn=DS      (open without authorizing -> S913 -> denial recovery; needs MVSMF_ABEND_TEST=1)\""
        " ] }\n");
  }

quit:
  return rc;
}

int testWildcardHandler(Session *session) {
  int rc = 0;
  char *filepath = NULL;

  filepath =
      (char *)http_get_env(session->httpc, (const UCHAR *)"HTTP_filepath");
  if (!filepath)
    filepath = "(null)";

  session->headers_sent = 1;
  if ((rc = http_resp(session->httpc, 200)) < 0)
    goto quit2;
  if ((rc = http_printf(session->httpc,
                        "Content-Type: application/json\r\n\r\n")) < 0)
    goto quit2;

  rc = http_printf(session->httpc,
                   "{ \"handler\": \"testWildcard\", \"filepath\": \"%s\" }\n",
                   filepath);

quit2:
  return rc;
}
